sudo: required
services:
 - docker

before_install:
  - docker build -t anttia/react-test -f ./client/Dockerfile.dev ./client
  - docker build myotherproject

script:
 - docker run anttia/react-test npm test -- --coverage

after_success:
 - docker build -t anttia/multi-client ./client
 - docker build -t anttia/multi-server ./server
 - docker build -t anttia/multi-nginx ./nginx
 - docker build -t anttia/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -U "$DOCKER_ID" --password-stdin
 - docker push anttia/multi-client
 - docker push anttia/multi-nginx
 - docker push anttia/multi-server
 - docker push anttia/multi-worker

